name: Deploy

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Magic
      # (replace ?version with current git commit ref
      # in order to invalidate the cache)
      - name: Do the magic
        run: |
          export GIT_HEAD=$(cat .git/ORIG_HEAD)
          sed -i "s/?version/?$GIT_HEAD/g" www/**/*.(html|js)
  
      # Deploy
      - name: Copying files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          rm: true
          source: www/
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 1 # remove "www/" on target
